language: php

php:
        - "5.4"
        - "5.5"
        - "5.6"

script: "./vendor/bin/tester tests/ -c ./tests/php-unix.ini"

before_script:
        - composer self-update
        - composer install --dev
        - mysql -u root < ./tests/data/databse.sql
        - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
