language: php

php:
        - "5.4"
        - "5.5"

matrix:
        allow_failures:
                - php: 5.6

script: "VERBOSE=true ./vendor/bin/tester tests/"

before_script:
        - composer self-update
        - composer install --dev